# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7aac8e382870718a3b38db7bf3b103ecccd152887737cb7dde7c714669a9ba462e28b866b731976d3fe0fa65f24221be78cc7e01b0c950a72bbf475c7f593c1

test:
  secret_key_base: a159bc0a92217d9e7551f9d05881dc6a1472fbcd8195991c945fe5d5319ba6f788bcdd67a12a5a31d4e6ee8f5af37ea98a099f74a287660c915361d7a319e101

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
